### PR TITLE
chore: ios platform version was set to 12.0

### PR DESCRIPTION
**Pull request by ashcherbonos**
## Description

AppNexusSDK 9.0.0 require iOS 12.0 or higher

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

### CODE REVIEW

**Comment by thekorn** [comment]
thanks @ashcherbonos ;)

**Comment by thekorn** [comment]
@ashcherbonos just pushed a new release with this change https://pub.dev/packages/xandr/versions/0.2.9

**Comment by ashcherbonos** [comment]
thanks!
i was not able to deploy pv build with current version of plugin to
appstore right now. hope its caused by this version mismatch…

**Comment by ashcherbonos** [comment]
Hi Markus.

I don't want to disturb you on your holiday. But since the Xandr package is
your hobby, can I ask you for a little help?



I am currently having 2 issues when trying to deploy a PV app to the
AppStore:


1. small one - PV app builds that use xandr package version 0.2.8 and above
are failing to publish to the AppStore.

Reason:

“The bundle at 'Payload\/Runner.app\/ANSDKResources.bundle' does not
contain a bundle executable. If this bundle intentionally does not contain
an executable, consider removing the CFBundleExecutable key from its
Info.plist and using a CFBundlePackageType of BNDL”

As I understand it, from version 9.0.0 AppNexusSDK changes the way it
distributes, so maybe we need to change some configuration in your plan?

2. Critical one! PV app (using gander package version 0.2.7) was rejected
by appstore with reason:

“ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file
contains invalid tracking information at the following path:
“Frameworks/SASDisplayKit.framework/PrivacyInfo.xcprivacy”.
NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn‘t empty.
Keys and values in your app’s privacy manifest must be valid. For more
details about privacy manifest files, visit:
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
.”


I look in my local pods, all
SASDisplayKit.framework/…/PrivacyInfo.xcprivacy  have

<key>NSPrivacyTracking</key>

<true/>


So, or we need PrivacyInfo.xcprivacy for the pv app itself (but what to
write there?) or something just got wrong, or I don’t understand anything



I need help.. pleeeeeees

**Pull request merged**
